var classes = [
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureDefaults",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "Illuminate\\Support\\Facades\\Date",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Validation\\Rules\\Password"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 27,
        "lloc": 17,
        "mi": 111.24,
        "mIwoC": 70.78,
        "commentWeight": 40.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 121,
        "totalStructuralComplexity": 363,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 363,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\FortifyServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureActions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureViews",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRateLimiting",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "Laravel\\Fortify\\Fortify",
            "Laravel\\Fortify\\Fortify",
            "Laravel\\Fortify\\Features",
            "Laravel\\Fortify\\Features",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Illuminate\\Validation\\Rules\\Password",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Illuminate\\Validation\\Rules\\Password",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Inertia\\Inertia",
            "Laravel\\Fortify\\Fortify",
            "Illuminate\\Cache\\RateLimiting\\Limit",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Laravel\\Fortify\\Fortify",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Str",
            "Illuminate\\Cache\\RateLimiting\\Limit",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Cache\\RateLimiting\\Limit",
            "Illuminate\\Support\\Facades\\RateLimiter"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 60,
        "vocabulary": 26,
        "volume": 282.03,
        "difficulty": 3.39,
        "effort": 956.44,
        "level": 0.29,
        "bugs": 0.09,
        "time": 53,
        "intelligentContent": 83.16,
        "number_operators": 8,
        "number_operands": 52,
        "number_operators_unique": 3,
        "number_operands_unique": 23,
        "cloc": 16,
        "loc": 57,
        "lloc": 41,
        "mi": 83.98,
        "mIwoC": 47.39,
        "commentWeight": 36.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.1,
        "relativeSystemComplexity": 841.1,
        "totalStructuralComplexity": 4205,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 4205.5,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "orders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 21,
        "vocabulary": 15,
        "volume": 82.04,
        "difficulty": 0.68,
        "effort": 55.67,
        "level": 1.47,
        "bugs": 0.03,
        "time": 3,
        "intelligentContent": 120.91,
        "number_operators": 2,
        "number_operands": 19,
        "number_operators_unique": 1,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 61.46,
        "mIwoC": 61.46,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 19,
        "package": "App\\Models\\",
        "pageRank": 0.12,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "products",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Illuminate\\Database\\Eloquent\\Relations\\BelongsTo",
            "Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 3,
        "length": 14,
        "vocabulary": 10,
        "volume": 46.51,
        "difficulty": 0.61,
        "effort": 28.42,
        "level": 1.64,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 76.1,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 60.81,
        "mIwoC": 60.81,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.8,
        "totalSystemComplexity": 49.8,
        "package": "App\\Models\\",
        "pageRank": 0.12,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User",
            "Laravel\\Fortify\\Contracts\\PasskeyUser"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [
            "Laravel\\Fortify\\Contracts\\PasskeyUser"
        ],
        "lcom": 1,
        "length": 14,
        "vocabulary": 11,
        "volume": 48.43,
        "difficulty": 0.65,
        "effort": 31.48,
        "level": 1.54,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 74.51,
        "number_operators": 1,
        "number_operands": 13,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 8,
        "loc": 17,
        "lloc": 9,
        "mi": 110.94,
        "mIwoC": 67.25,
        "commentWeight": 43.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Models\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\HandleInertiaRequests",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "version",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "share",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Inertia\\Middleware",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "Inertia\\Middleware"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 12,
        "volume": 71.7,
        "difficulty": 2.67,
        "effort": 191.2,
        "level": 0.38,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 26.89,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 19,
        "loc": 32,
        "lloc": 13,
        "mi": 108.93,
        "mIwoC": 62.44,
        "commentWeight": 46.49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 51,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\HandleAppearance",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Response",
            "Illuminate\\Http\\Request",
            "Closure",
            "Illuminate\\Support\\Facades\\View"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 108.98,
        "mIwoC": 69.03,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Settings\\ProfileDeleteRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 114.27,
        "mIwoC": 74.31,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Http\\Requests\\Settings\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Settings\\ProfileUpdateRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 115.66,
        "mIwoC": 75.71,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "App\\Http\\Requests\\Settings\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Settings\\PasswordUpdateRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 112,
        "mIwoC": 72.05,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "App\\Http\\Requests\\Settings\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Settings\\TwoFactorAuthenticationRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 210.96,
        "mIwoC": 171,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Requests\\Settings\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\StoreOrderRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 18,
        "volume": 104.25,
        "difficulty": 0.68,
        "effort": 70.52,
        "level": 1.48,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 154.11,
        "number_operators": 2,
        "number_operands": 23,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 5,
        "loc": 17,
        "lloc": 12,
        "mi": 99.43,
        "mIwoC": 62.19,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\UpdateProductRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 42,
        "vocabulary": 25,
        "volume": 195.04,
        "difficulty": 0.83,
        "effort": 162.53,
        "level": 1.2,
        "bugs": 0.07,
        "time": 9,
        "intelligentContent": 234.05,
        "number_operators": 2,
        "number_operands": 40,
        "number_operators_unique": 1,
        "number_operands_unique": 24,
        "cloc": 5,
        "loc": 17,
        "lloc": 12,
        "mi": 97.53,
        "mIwoC": 60.29,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 19,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\UpdateOrderRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 18,
        "volume": 104.25,
        "difficulty": 0.68,
        "effort": 70.52,
        "level": 1.48,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 154.11,
        "number_operators": 2,
        "number_operands": 23,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 5,
        "loc": 17,
        "lloc": 12,
        "mi": 99.43,
        "mIwoC": 62.19,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Api\\StoreOrderRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 14,
        "volume": 87.57,
        "difficulty": 0.81,
        "effort": 70.73,
        "level": 1.24,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 108.42,
        "number_operators": 2,
        "number_operands": 21,
        "number_operators_unique": 1,
        "number_operands_unique": 13,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 94.66,
        "mIwoC": 62.72,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\Api\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Api\\UpdateOrderStatusRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 7,
        "vocabulary": 6,
        "volume": 18.09,
        "difficulty": 0.5,
        "effort": 9.05,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 36.19,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 99.46,
        "mIwoC": 67.52,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\Api\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\StoreProductRequest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "implements": [],
        "lcom": 2,
        "length": 39,
        "vocabulary": 23,
        "volume": 176.42,
        "difficulty": 0.84,
        "effort": 148.35,
        "level": 1.19,
        "bugs": 0.06,
        "time": 8,
        "intelligentContent": 209.8,
        "number_operators": 2,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 22,
        "cloc": 5,
        "loc": 17,
        "lloc": 12,
        "mi": 97.83,
        "mIwoC": 60.59,
        "commentWeight": 37.24,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Settings\\SecurityController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Inertia\\Response",
            "App\\Http\\Requests\\Settings\\TwoFactorAuthenticationRequest",
            "Laravel\\Fortify\\Features",
            "Laravel\\Fortify\\Features",
            "Laravel\\Fortify\\Features",
            "Illuminate\\Validation\\Rules\\Password",
            "Laravel\\Fortify\\Features",
            "Laravel\\Fortify\\Features",
            "Laravel\\Fortify\\Features",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\Settings\\PasswordUpdateRequest",
            "Inertia\\Inertia"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 47,
        "vocabulary": 28,
        "volume": 225.95,
        "difficulty": 2.46,
        "effort": 555.83,
        "level": 0.41,
        "bugs": 0.08,
        "time": 31,
        "intelligentContent": 91.85,
        "number_operators": 6,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 25,
        "cloc": 6,
        "loc": 26,
        "lloc": 20,
        "mi": 88.6,
        "mIwoC": 54.73,
        "commentWeight": 33.87,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 400.14,
        "totalStructuralComplexity": 800,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 800.29,
        "package": "App\\Http\\Controllers\\Settings\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Settings\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Inertia\\Response",
            "Illuminate\\Http\\Request",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\Settings\\ProfileUpdateRequest",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\Settings\\ProfileDeleteRequest",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 33,
        "vocabulary": 16,
        "volume": 132,
        "difficulty": 3.12,
        "effort": 411.23,
        "level": 0.32,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 42.37,
        "number_operators": 6,
        "number_operands": 27,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 9,
        "loc": 36,
        "lloc": 27,
        "mi": 88.63,
        "mIwoC": 53.66,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 169.29,
        "totalStructuralComplexity": 507,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 507.86,
        "package": "App\\Http\\Controllers\\Settings\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.06,
        "afferentCoupling": 6,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "availableProducts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareItems",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\OrderService",
            "Inertia\\Response",
            "App\\Models\\Order",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\StoreOrderRequest",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\DB",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "App\\Models\\Order",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "App\\Models\\Order",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\UpdateOrderRequest",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\DB",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\DB",
            "Inertia\\Inertia",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Database\\Eloquent\\Collection",
            "App\\Models\\Product",
            "App\\Models\\Product"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 191,
        "vocabulary": 55,
        "volume": 1104.24,
        "difficulty": 8.1,
        "effort": 8944.34,
        "level": 0.12,
        "bugs": 0.37,
        "time": 497,
        "intelligentContent": 136.33,
        "number_operators": 29,
        "number_operands": 162,
        "number_operators_unique": 5,
        "number_operands_unique": 50,
        "cloc": 7,
        "loc": 86,
        "lloc": 79,
        "mi": 58.42,
        "mIwoC": 37.03,
        "commentWeight": 21.39,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1024,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 1024.36,
        "totalStructuralComplexity": 11264,
        "totalDataComplexity": 3.94,
        "totalSystemComplexity": 11267.94,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "productAttributes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\ProductService",
            "Inertia\\Response",
            "App\\Models\\Product",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\StoreProductRequest",
            "App\\Models\\Product",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "App\\Models\\Product",
            "Inertia\\Inertia",
            "Inertia\\Response",
            "App\\Models\\Product",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\UpdateProductRequest",
            "App\\Models\\Product",
            "Inertia\\Inertia",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Models\\Product",
            "Illuminate\\Support\\Facades\\DB",
            "Inertia\\Inertia",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 8,
        "length": 80,
        "vocabulary": 30,
        "volume": 392.55,
        "difficulty": 3.72,
        "effort": 1461.16,
        "level": 0.27,
        "bugs": 0.13,
        "time": 81,
        "intelligentContent": 105.46,
        "number_operators": 13,
        "number_operands": 67,
        "number_operators_unique": 3,
        "number_operands_unique": 27,
        "cloc": 4,
        "loc": 59,
        "lloc": 55,
        "mi": 63.37,
        "mIwoC": 43.74,
        "commentWeight": 19.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.55,
        "relativeSystemComplexity": 289.55,
        "totalStructuralComplexity": 2890,
        "totalDataComplexity": 5.5,
        "totalSystemComplexity": 2895.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Api\\OrderApiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\OrderService",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\JsonResponse",
            "App\\Models\\Order",
            "Illuminate\\Http\\JsonResponse",
            "App\\Http\\Requests\\Api\\StoreOrderRequest",
            "Illuminate\\Http\\JsonResponse",
            "App\\Http\\Requests\\Api\\UpdateOrderStatusRequest",
            "App\\Models\\Order"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 11,
        "volume": 79.57,
        "difficulty": 0.95,
        "effort": 75.59,
        "level": 1.05,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 83.75,
        "number_operators": 4,
        "number_operands": 19,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 23,
        "lloc": 23,
        "mi": 56.85,
        "mIwoC": 56.85,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 3.13,
        "totalSystemComplexity": 248.13,
        "package": "App\\Http\\Controllers\\Api\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Api\\ProductApiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\ProductService",
            "Illuminate\\Http\\JsonResponse",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 12,
        "volume": 71.7,
        "difficulty": 1.8,
        "effort": 129.06,
        "level": 0.56,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 39.83,
        "number_operators": 2,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 63.2,
        "mIwoC": 63.2,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "package": "App\\Http\\Controllers\\Api\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Actions\\Fortify\\ResetUserPassword",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "reset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Laravel\\Fortify\\Contracts\\ResetsUserPasswords",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Validator"
        ],
        "parents": [],
        "implements": [
            "Laravel\\Fortify\\Contracts\\ResetsUserPasswords"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 4,
        "volume": 18,
        "difficulty": 0,
        "effort": 0,
        "level": 0.89,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 5,
        "loc": 15,
        "lloc": 10,
        "mi": 108.25,
        "mIwoC": 69.26,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 25.33,
        "package": "App\\Actions\\Fortify\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Actions\\Fortify\\CreateNewUser",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Laravel\\Fortify\\Contracts\\CreatesNewUsers",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Validator",
            "App\\Models\\User"
        ],
        "parents": [],
        "implements": [
            "Laravel\\Fortify\\Contracts\\CreatesNewUsers"
        ],
        "lcom": 1,
        "length": 15,
        "vocabulary": 6,
        "volume": 38.77,
        "difficulty": 1.4,
        "effort": 54.28,
        "level": 0.71,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 27.7,
        "number_operators": 1,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 5,
        "loc": 15,
        "lloc": 10,
        "mi": 105.92,
        "mIwoC": 66.93,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 25.33,
        "package": "App\\Actions\\Fortify\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getListPaginated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findWithRelations",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Contracts\\Pagination\\LengthAwarePaginator",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "App\\Models\\Product",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Order",
            "App\\Models\\Order"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 119,
        "vocabulary": 40,
        "volume": 633.31,
        "difficulty": 8.65,
        "effort": 5476.26,
        "level": 0.12,
        "bugs": 0.21,
        "time": 304,
        "intelligentContent": 73.24,
        "number_operators": 21,
        "number_operands": 98,
        "number_operators_unique": 6,
        "number_operands_unique": 34,
        "cloc": 10,
        "loc": 53,
        "lloc": 43,
        "mi": 75.38,
        "mIwoC": 44.21,
        "commentWeight": 31.16,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.32,
        "relativeSystemComplexity": 361.33,
        "totalStructuralComplexity": 1444,
        "totalDataComplexity": 1.3,
        "totalSystemComplexity": 1445.3,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getListPaginated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Illuminate\\Contracts\\Pagination\\LengthAwarePaginator",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 16,
        "volume": 124,
        "difficulty": 6.9,
        "effort": 855.6,
        "level": 0.14,
        "bugs": 0.04,
        "time": 48,
        "intelligentContent": 17.97,
        "number_operators": 8,
        "number_operands": 23,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 3,
        "loc": 18,
        "lloc": 15,
        "mi": 88.7,
        "mIwoC": 59.15,
        "commentWeight": 29.56,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 16.6,
        "package": "App\\Services\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Concerns\\ProfileValidationRules",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "profileRules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nameRules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "emailRules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Validation\\Rule",
            "Illuminate\\Validation\\Rule"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 9,
        "volume": 63.4,
        "difficulty": 2.29,
        "effort": 144.91,
        "level": 0.44,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 27.74,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 15,
        "loc": 31,
        "lloc": 16,
        "mi": 104.89,
        "mIwoC": 60.85,
        "commentWeight": 44.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 16.73,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.2,
        "totalSystemComplexity": 50.2,
        "package": "App\\Concerns\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Concerns\\PasswordValidationRules",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "passwordRules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "currentPasswordRules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Validation\\Rules\\Password"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0.75,
        "effort": 13.93,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 24.77,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 10,
        "loc": 22,
        "lloc": 12,
        "mi": 110.67,
        "mIwoC": 67.44,
        "commentWeight": 43.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Concerns\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]